# docker-compose.yml
version: '2'


networks:
  micro_network:
    name: micro_network
    external: True

services:
  sema-classifier:
    container_name: sema-classifier
    image: sema-classifier:latest
    command: ../docker_startup.sh 0
    build:
      context: .
      dockerfile: ./sema_classifier/Dockerfile
    ports:
      - "5002:5002"
    restart: always
    volumes:
      - ${PWD}/sema_classifier/:/sema-classifier
      - ${PWD}/submodules/SEMA-quickspan:/sema-classifier/application/submodules/SEMA-quickspan
      - ${PWD}/submodules/bingraphvis:/sema-classifier/application/submodules/bingraphvis 
      - ${PWD}/penv-fix/:/sema-classifier/application/penv-fix 
      - ${PWD}/database/:/sema-classifier/application/database
      - ${PWD}/yara/:/sema-classifier/application/yara
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$(DISPLAY) 
    networks:
      - micro_network

      

  